export const AUDIT_LOG = {
	COMPLAINT_SUBMITTED: 'complaint.submitted',
	COMPLAINT_RESPONDED: 'complaint.responded',
	COMPLAINT_STATUS_CHANGED: 'complaint.status_changed',
	COMPLAINT_TRACKING_VIEWED: 'complaint.tracking_viewed',
	COMPLAINT_RECEIPT_DELIVERY_FAILED: 'complaint.receipt_delivery_failed',
	COMPLAINT_RESPONSE_DELIVERY_FAILED: 'complaint.response_delivery_failed',
	COMPLAINT_AI_CLASSIFIED: 'complaint.ai_classified',
	COMPLAINT_AI_CLASSIFICATION_FAILED: 'complaint.ai_classification_failed',
	USER_INVITED: 'user.invited',
	USER_ACCESS_UPDATED: 'user.access_updated',
	USER_REMOVED: 'user.removed',
	USER_LOGIN_SUCCESS: 'user.login_success',
	USER_LOGIN_FAILED: 'user.login_failed',
	USER_JOINED_ORGANIZATION: 'user.joined_organization',
	INVITATION_REVOKED: 'invitation.revoked',
	INVITATION_ACCEPTED: 'invitation.accepted',
	ROLE_CREATED: 'role.created',
	ROLE_UPDATED: 'role.updated',
	ROLE_DELETED: 'role.deleted',
	PERMISSION_CREATED: 'permission.created',
	PERMISSION_UPDATED: 'permission.updated',
	PERMISSION_DELETED: 'permission.deleted',
	STORE_CREATED: 'store.created',
	STORE_UPDATED: 'store.updated',
	STORE_DEACTIVATED: 'store.deactivated',
	STORE_FORM_ENABLED: 'store.form_enabled',
	STORE_FORM_DISABLED: 'store.form_disabled',
	ORGANIZATION_CREATED: 'organization.created',
	ORGANIZATION_UPDATED: 'organization.updated',
	ORGANIZATION_FORM_ENABLED: 'organization.form_enabled',
	ORGANIZATION_FORM_DISABLED: 'organization.form_disabled',
	ORGANIZATION_TEST_EMAIL_SENT: 'organization.test_email.sent',
	WEBHOOK_CREATED: 'webhook.created',
	WEBHOOK_UPDATED: 'webhook.updated',
	WEBHOOK_DELETED: 'webhook.deleted',
	API_KEY_GENERATED: 'api_key.generated',
	API_KEY_REGENERATED: 'api_key.regenerated',
} as const

export type AuditLogAction = (typeof AUDIT_LOG)[keyof typeof AUDIT_LOG]
